[project]
name = "vlm-manga109"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "transformers>=4.53.0",
    "unsloth>=2025.6.8",
]
